Notification services
bigdatapoc/microservice-ecms pull request #1
Opened 2018-06-08 10:19 UTC by HarryFromSpace

This pull request contains following functionality:
1. Installed RabbitMQ in docker container.  
2. Nofitication framework spring boot application with RabbitMQ listener which is subscribing RabbitMQ data queue.

Tested as follows:
1.

2018-06-08 10:40 UTC, tanushreeyadav commented on microservice-ecms-notification/src/main/java/com/ecms/MicroserviceEcmsNotificationApplication.java
> +// @EnableDiscoveryClient
Why committing commented code? please remove it.

2018-06-08 10:43 UTC, tanushreeyadav requested changes
Please make the changes as added in comments.

2018-06-08 10:43 UTC, tanushreeyadav commented on microservice-ecms-notification/src/main/java/com/ecms/configuration/RabbitMqConfig.java
> +@Configuration
Please define class level comments.

2018-06-08 11:05 UTC, bigdatapoc commented on microservice-ecms-notification/src/main/java/com/ecms/service/NotificationService.java
> +			e.printStackTrace();
Need to use log no e.printStackTrace

2018-06-18 06:27 UTC, HarryFromSpace commented on microservice-ecms-notification/src/main/resources/application.properties
> +#RabbitMQ
hi

2018-06-21 08:02 UTC, closed without merging